apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "carib-clear.name" . }}-config
  labels:
    {{- include "carib-clear.labels" . | nindent 4 }}
data:
  allowed-origins: {{ .Values.api.env.allowedOrigins | quote }}
