apiVersion: v1
kind: Secret
metadata:
  name: {{ template "carib-clear.name" . }}-secrets
  labels:
    {{- include "carib-clear.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.global.database.url | quote }}
  {{- if .Values.api.env.apiKey }}
  api-key: {{ .Values.api.env.apiKey | quote }}
  {{- end }}
  {{- if .Values.api.env.secretBackend }}
  secret-backend: {{ .Values.api.env.secretBackend | quote }}
  {{- end }}
  {{- if .Values.api.env.webhookSecret }}
  webhook-secret: {{ .Values.api.env.webhookSecret | quote }}
  {{- end }}
