{{- if .Values.global.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "carib-clear.name" . }}-{{ .Values.global.environment }}
  labels:
    {{- include "carib-clear.labels" . | nindent 4 }}
{{- end -}}
