#!/usr/bin/env python3
"""
prepare_validation_batch.py
Extract 20 random samples per domain from kreyol-instructions-v1.jsonl
and format them as a human-readable review document for Haitian Creole speakers.

Output:
    data/processed/validation-batch.md  (for humans)
    data/processed/validation-batch.jsonl  (for programmatic processing)

Reviewer workflow:
    1. Open validation-batch.md
    2. For each Q&A pair, rate 1-5 and flag issues
    3. Save as validation-batch-reviewed.md
    4. We then filter instructions.jsonl to only validated=True
"""

import argparse
import json
import os
import random
from collections import defaultdict

random.seed(2025)  # reproducible sample

DOMAINS = ["agriculture", "civic", "education", "general", "health"]
SAMPLES_PER_DOMAIN = 20


def load_instructions(path: str) -> list[dict]:
    records = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return records


def stratified_sample(records: list[dict], per_domain: int) -> dict:
    by_domain = defaultdict(list)
    for r in records:
        by_domain[r.get("domain", "general")].append(r)

    sampled = {}
    for domain in DOMAINS:
        pool = by_domain.get(domain, [])
        seen_instructions = set()
        unique = []
        for item in pool:
            instruction_key = item.get("instruction", "").strip()
            if instruction_key and instruction_key not in seen_instructions:
                seen_instructions.add(instruction_key)
                unique.append(item)
        pool = unique
        if len(pool) <= per_domain:
            sampled[domain] = pool
        else:
            sampled[domain] = random.sample(pool, per_domain)
    return sampled


def format_review_md(sampled: dict, output_path: str):
    lines = [
        "# Kreyol-AI Instruction Validation Batch",
        "",
        "**Reviewer:** ___________________________  ",
        "**Date:** ___________________________  ",
        "**Native Kreyol speaker:** Yes / No  ",
        "",
        "---",
        "",
        "## Instructions",
        "",
        "For each Q&A pair below, rate **grammaticality** and **naturalness** on a 1-5 scale:",
        "",
        "| Score | Meaning |",
        "|-------|---------|",
        "| 1 | Broken / nonsense Kreyol |",
        "| 2 | Understandable but clearly off |",
        "| 3 | Acceptable but awkward |",
        "| 4 | Natural, good Kreyol |",
        "| 5 | Perfect, sounds like a real Haitian speaker |",
        "",
        "Also flag:",
        "- `[GRAMMAR]` if grammar is wrong",
        "- `[CULTURE]` if culturally inappropriate or weird",
        "- `[SAFETY]` if advice is dangerous or misleading",
        "- `[FRENCH]` if it's French disguised as Kreyol",
        "",
        "---",
        "",
    ]

    for domain in DOMAINS:
        lines.append(f"## Domain: {domain.upper()} ({len(sampled[domain])} samples)")
        lines.append("")
        for i, item in enumerate(sampled[domain], 1):
            lines.append(f"### Sample {i}")
            lines.append("")
            lines.append(f"**Q:** {item['instruction']}")
            lines.append("")
            lines.append(f"**A:** {item['response']}")
            lines.append("")
            lines.append("Rating: __/5   Flags: _______________")
            lines.append("")
            lines.append("Notes (optional):")
            lines.append("> ")
            lines.append("")
            lines.append("---")
            lines.append("")

    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Total samples reviewed: {sum(len(v) for v in sampled.values())}")
    for domain in DOMAINS:
        lines.append(f"- {domain}: _____ / {len(sampled[domain])} passing (score ≥ 3)")
    lines.append("")
    lines.append("**Overall recommendation:** (Keep all / Discard X% / Rewrite domain X)")
    lines.append("")
    lines.append("---")
    lines.append("*Generated by prepare_validation_batch.py*")

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Review document → {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Prepare instruction validation batch")
    parser.add_argument(
        "--input", "-i",
        default="data/processed/kreyol-instructions-v1.jsonl",
        help="Input instructions jsonl"
    )
    parser.add_argument(
        "--output-md", "-o",
        default="data/processed/validation-batch.md",
        help="Output markdown review document"
    )
    parser.add_argument(
        "--output-jsonl",
        default="data/processed/validation-batch.jsonl",
        help="Output sampled jsonl for programmatic use"
    )
    parser.add_argument(
        "--per-domain", "-n", type=int, default=SAMPLES_PER_DOMAIN,
        help="Samples per domain (default: 20)"
    )
    args = parser.parse_args()

    records = load_instructions(args.input)
    if not records:
        print("[ERROR] No instructions found. Run generate_instructions.py first.")
        return

    sampled = stratified_sample(records, args.per_domain)
    format_review_md(sampled, args.output_md)

    # Also save the sampled records as jsonl
    with open(args.output_jsonl, "w", encoding="utf-8") as f:
        for domain in DOMAINS:
            for item in sampled[domain]:
                f.write(json.dumps(item, ensure_ascii=False) + "\n")
    print(f"Sampled jsonl  → {args.output_jsonl}")

    total = sum(len(v) for v in sampled.values())
    print(f"\n✓ Prepared {total} samples ({args.per_domain} per domain "
          f"across {len(DOMAINS)} domains)")
    print("  Send validation-batch.md to a Haitian Creole speaker for review.")


if __name__ == "__main__":
    main()
