from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Set
import time

from jarvis.knowledge.drift_checker import (
    DriftChecker,
    DriftReport,
    HermesCapabilitySource,
    _JARVIS_EXTRA_CAPABILITIES,
)
from jarvis.runtime.local_runner import LocalCapabilityRunner


@dataclass
class SelfKnowledge:
    """Structured self-knowledge document for JARVIS."""

    capabilities: Dict[str, List[Dict[str, Any]]] = field(default_factory=dict)
    """Categories -> list of capabilities with name, status, drift indicator."""

    tools: Dict[str, List[Dict[str, Any]]] = field(default_factory=dict)
    """Tool categories -> list of tools with name, description, available."""

    limits: List[str] = field(default_factory=list)
    """Known limitations / constraints."""

    system_summary: Dict[str, Any] = field(default_factory=dict)
    """System info: OS, CPU, memory."""

    drift: DriftReport | None = None
    """Latest drift report, if available."""

    generated_at: float = field(default_factory=time.time)

    def to_markdown(self) -> str:
        """Render as structured markdown document."""
        lines: List[str] = [
            "# JARVIS Self-Knowledge",
            "",
            f"*Generated: {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime(self.generated_at))}*",
            "",
            "---",
            "",
            "## System Overview",
            "",
        ]

        # System summary
        if self.system_summary:
            for k, v in self.system_summary.items():
                label = k.replace("_", " ").title()
                lines.append(f"- **{label}:** {v}")
            lines.append("")

        # Drift status
        if self.drift:
            status = "⚠️ DRIFTED" if self.drift.missing or self.drift.unexpected else "✅ In Sync"
            lines.append(f"**Capability Status:** {status}")
            if self.drift.missing:
                lines.append(f"- **Missing ({len(self.drift.missing)}):** `{'`, `'.join(self.drift.missing)}`")
            if self.drift.unexpected:
                lines.append(f"- **Unexpected ({len(self.drift.unexpected)}):** `{'`, `'.join(self.drift.unexpected)}`")
            lines.append("")

        lines.append("---")
        lines.append("")

        # Capabilities by category
        lines.append("## Capabilities")
        lines.append("")
        if not self.capabilities:
            lines.append("_No capabilities reported._")
        else:
            for category, caps in sorted(self.capabilities.items()):
                heading = category.replace("_", " ").title()
                lines.append(f"### {heading}")
                lines.append("")
                for cap in caps:
                    name = cap.get("name", "?")
                    status_icon = "✅" if cap.get("available") else "❌"
                    drift_tag = " **[DRIFTED — unavailable]**" if cap.get("drifted") else ""
                    desc = cap.get("description", "")
                    if desc:
                        lines.append(f"- {status_icon} `{name}`{drift_tag} — {desc}")
                    else:
                        lines.append(f"- {status_icon} `{name}`{drift_tag}")
                lines.append("")

        lines.append("---")
        lines.append("")

        # Tools
        lines.append("## Tools")
        lines.append("")
        if not self.tools:
            lines.append("_No tools reported._")
        else:
            for category, tool_list in sorted(self.tools.items()):
                heading = category.replace("_", " ").title()
                lines.append(f"### {heading}")
                lines.append("")
                for tool in tool_list:
                    name = tool.get("name", "?")
                    available = tool.get("available", False)
                    icon = "✅" if available else "❌"
                    desc = tool.get("description", "")
                    timeout = tool.get("timeout")
                    if timeout:
                        desc += f" (timeout: {timeout}s)"
                    if desc:
                        lines.append(f"- {icon} `{name}` — {desc}")
                    else:
                        lines.append(f"- {icon} `{name}`")
                lines.append("")

        lines.append("---")
        lines.append("")

        # Limits
        lines.append("## Known Limitations")
        lines.append("")
        if not self.limits:
            lines.append("_No limitations reported._")
        else:
            for limit in self.limits:
                lines.append(f"- {limit}")
        lines.append("")

        lines.append("---")
        lines.append("")
        lines.append(f"_Report generated by JARVIS Self-Knowledge module at `{time.strftime('%H:%M:%S UTC', time.gmtime(self.generated_at))}`_")

        return "\n".join(lines)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dict for API responses."""
        return {
            "generated_at": self.generated_at,
            "system_summary": self.system_summary,
            "drift": {
                "missing": self.drift.missing if self.drift else [],
                "unexpected": self.drift.unexpected if self.drift else [],
                "checked_at": self.drift.checked_at if self.drift else None,
            } if self.drift else None,
            "capability_count": sum(len(caps) for caps in self.capabilities.values()),
            "tool_count": sum(len(tools) for tools in self.tools.values()),
        }


class SelfKnowledgeBuilder:
    """Builds a SelfKnowledge document from live sources."""

    def __init__(
        self,
        drift_checker: DriftChecker | None = None,
        local_runner: LocalCapabilityRunner | None = None,
    ) -> None:
        self._drift_checker = drift_checker or DriftChecker(HermesCapabilitySource())
        self._local_runner = local_runner or LocalCapabilityRunner()

    def build(self) -> SelfKnowledge:
        """Gather all data and produce a SelfKnowledge document."""
        drift = self._drift_checker.run()
        source = self._drift_checker.source

        # Capabilities by category
        capabilities: Dict[str, List[Dict[str, Any]]] = {}
        expected = source.expected()
        observed = source.observed()

        # Hermes built-in tools
        hermes_tools = [t for t in expected if t not in _JARVIS_EXTRA_CAPABILITIES]
        capabilities["hermes_tools"] = [
            {
                "name": t,
                "available": t in observed,
                "drifted": t not in observed,
                "description": "Hermes built-in tool",
            }
            for t in sorted(hermes_tools)
        ]

        # Hermes skills — from the source details
        skill_details = source.skill_details() if hasattr(source, 'skill_details') else []
        skill_names = {s["name"] for s in skill_details}
        all_skills = expected & {s["name"] for s in skill_details} if skill_details else set()
        capabilities["skills"] = [
            {
                "name": s.get("name", "?"),
                "category": s.get("category", ""),
                "available": s.get("status", "enabled") != "disabled",
                "drifted": s.get("status", "enabled") == "disabled",
                "description": f"Hermes skill ({s.get('category', 'uncategorized')})",
            }
            for s in sorted(skill_details, key=lambda x: x.get("name", ""))
        ]

        # JARVIS extras
        jarvis_extra_names = _JARVIS_EXTRA_CAPABILITIES
        capabilities["jarvis_extras"] = [
            {
                "name": cap,
                "available": cap in observed,
                "drifted": cap not in observed,
                "description": _jarvis_cap_description(cap),
            }
            for cap in sorted(jarvis_extra_names)
        ]

        # Local tools
        local_tools = self._local_runner.list_tools()
        local_tool_names = [t["name"] for t in local_tools]
        tools: Dict[str, List[Dict[str, Any]]] = {
            "local_runner": [
                {
                    "name": t["name"],
                    "description": t.get("description", ""),
                    "available": True,
                    "timeout": t.get("timeout"),
                }
                for t in sorted(local_tools, key=lambda x: x["name"])
            ]
        }

        # System summary
        sys_result = self._local_runner.run("system_info")
        system_summary: Dict[str, Any] = {}
        if sys_result.ok:
            system_summary = sys_result.data or {}

        # Limits
        limits: List[str] = []
        if drift.missing:
            limits.append(f"Cannot use {len(drift.missing)} drifted capabilities (missing: {', '.join(drift.missing[:5])})")
        limits.append("Requires Hermes CLI for remote/skill-based tools")
        limits.append("Network access limited to local runner tools for file operations")
        if system_summary.get("memory_gb", 0) and system_summary["memory_gb"] < 4:
            limits.append("Low memory — may impact performance with large models")

        return SelfKnowledge(
            capabilities=capabilities,
            tools=tools,
            limits=limits,
            system_summary=system_summary,
            drift=drift,
        )


def _jarvis_cap_description(cap: str) -> str:
    """Map capability shortcut to human-readable description."""
    descriptions = {
        "drift_check": "Compare expected vs observed capabilities for drift",
        "approval_queue": "Manage pending approval requests for high-risk actions",
        "event_logging": "Log events to JSONL and SQLite for auditability",
        "voice_input": "Capture speech via microphone with VAD and Whisper STT",
        "voice_output": "Speak responses via Piper TTS",
        "policy_gating": "Evaluate actions against security policy before execution",
        "hermes_cli_bridge": "Invoke Hermes CLI for tool execution and skill queries",
    }
    return descriptions.get(cap, f"JARVIS custom capability: {cap}")